In [ ]:
import io
import requests
import regex as re
import numpy as np
import pandas as pd  # MANIPULAR BASES DE DADOS
import seaborn as sns  # GRAPHICS GENERATION
from sklearn import metrics  # METHODS TO EVALUATE THE BEST AI TEST PERFORMANCE
import matplotlib.pyplot as plt  # GRAPHICS GENERATION
from IPython.display import display
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression  # AI TRAINING TEST
from sklearn.ensemble import RandomForestRegressor  # AI TRAINING TEST
from sklearn.model_selection import train_test_split  # AI LIBRARY
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
# import warnings
# warnings.filterwarnings('ignore')

1. Faça a leitura do arquivo "Churn_Modelling_2.csv " disponível na pasta "Churn " no repositório GitHub da disciplina  e armazene numa variável como um dataframe;

In [ ]:
churn2_url = 'https://raw.githubusercontent.com/malegopc/DSBD/main/Datasets/Churn/Churn_Modelling_2.csv'
churn2_csv = requests.get(churn2_url).content
churn2_dataset = pd.read_csv(io.StringIO(churn2_csv.decode('utf-8')))
churn2 = pd.DataFrame(churn2_dataset)
churn2

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

2. Elimine instâncias (linhas) com dados ausentes para a variável "IsActiveMember".

In [ ]:
# churn2["IsActiveMember"].dropna()
# churn2
churn2 = churn2[churn2['IsActiveMember'].notna()]
churn2

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[9986 rows x 14 columns]

3. Faça a imputação dos dados ausentes para a variável "NumOfProducts" utilizando a média da variável.

In [ ]:
# strategy: mean, median, most_frequent, constant
imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')
churn2[['NumOfProducts']] = imputer.fit_transform(churn2[['NumOfProducts']].values)
churn2

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3678: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)


RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[9986 rows x 14 columns]

4. Crie uma variável (array) X que contenha os valores apenas dos atributos/colunas de "CreditScore" a "EstimatedSalary" utilizando a função "iloc" do Pandas. Em outras palavras, crie uma variável X que receba o dataframe inteiro exceto as 3 primeiras colunas e a última. Observe que as 3 primeiras colunas "RowNumber", "CustomerId" e "Surname" não são importantes e devem ser descartadas. E a última coluna ("Exited") será a variável destino ("target" ou saída) que será criada no próximo passo;

In [ ]:
x = churn2.iloc[:, 3:13]
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00            1.0   
1             608     Spain  Female   41       1   83807.86            1.0   
2             502    France  Female   42       8  159660.80            3.0   
3             699    France  Female   39       1       0.00            2.0   
4             850     Spain  Female   43       2  125510.82            1.0   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00            2.0   
9996          516    France    Male   35      10   57369.61            1.0   
9997          709    France  Female   36       7       0.00            1.0   
9998          772   Germany    Male   42       3   75075.31            2.0   
9999          792    France  Female   28       4  130142.79            1.0   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1             1.0        101348.88  
1             0             1.0        112542.58  
2             1             0.0        113931.57  
3             0             0.0         93826.63  
4             1             1.0         79084.10  
...         ...             ...              ...  
9995          1             0.0         96270.64  
9996          1             1.0        101699.77  
9997          0             1.0         42085.58  
9998          1             0.0         92888.52  
9999          1             0.0         38190.78  

[9986 rows x 10 columns]

5. Crie uma variável (array) y que contenha apenas a última coluna ("Exited"). Esta é a variável destino ("target" ou saída);

In [ ]:
y = churn2.iloc[:,-1]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 9986, dtype: int64

6. Codifique a coluna/variável categórica "Geography" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

In [ ]:
# Geography = ["France", "Spain", "Germany"] #variável categórica
Geography = churn2["Geography"]
le = LabelEncoder() # cria objeto
le.fit(Geography) # ajusta na variável de entrada
churn2["Geography"] = le.transform(Geography) # aplica a transformação na variável de entrada
churn2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602   Hargrave          619          0  Female   42   
1             2    15647311       Hill          608          2  Female   41   
2             3    15619304       Onio          502          0  Female   42   
3             4    15701354       Boni          699          0  Female   39   
4             5    15737888   Mitchell          850          2  Female   43   
...         ...         ...        ...          ...        ...     ...  ...   
9995       9996    15606229   Obijiaku          771          0    Male   39   
9996       9997    15569892  Johnstone          516          0    Male   35   
9997       9998    15584532        Liu          709          0  Female   36   
9998       9999    15682355  Sabbatini          772          1    Male   42   
9999      10000    15628319     Walker          792          0  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[9986 rows x 14 columns]

7. Codifique a coluna/variável categórica "Gender" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

In [ ]:
# Gender = ["Male", "Female"] #variável categórica
Gender = churn2["Gender"]
le = LabelEncoder() # cria objeto
le.fit(Gender) # ajusta na variável de entrada
churn2["Gender"] = le.transform(Gender) # aplica a transformação na variável de entrada
churn2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602   Hargrave          619          0       0   42   
1             2    15647311       Hill          608          2       0   41   
2             3    15619304       Onio          502          0       0   42   
3             4    15701354       Boni          699          0       0   39   
4             5    15737888   Mitchell          850          2       0   43   
...         ...         ...        ...          ...        ...     ...  ...   
9995       9996    15606229   Obijiaku          771          0       1   39   
9996       9997    15569892  Johnstone          516          0       1   35   
9997       9998    15584532        Liu          709          0       0   36   
9998       9999    15682355  Sabbatini          772          1       1   42   
9999      10000    15628319     Walker          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[9986 rows x 14 columns]

8. Após executar o passo 6, transforme os dados da variável "Geography" para a forma binária utilizando a classe OneHotEncoder da biblioteca scikit-learn eliminando redundância, ou seja, aplicando a codificação de variáveis dummy. Observe que há apenas 3 países (categorias) diferentes. 
Atenção: esse talvez seja o passo mais difícil da tarefa. Você deve transformar o resultado da variável/coluna "Geography" obtido no passo 6 para o formato binário (one-hot) de modo que fique representado por apenas duas colunas (de 0s e 1s). Além disso, essas duas novas colunas devem permanecer na mesma variável X. Dica: verifique a utilização da função make_column_transformer (Links para um site externo.) da biblioteca scikit-learn;

In [ ]:
X = churn2.iloc[:,[4]] # COLUNA GEOGRAPHY SE ENCONTRA NA 4ª POSIÇÃO
enc = OneHotEncoder(sparse = False) # cria objeto com argumento sparse = False para retornar uma matriz
enc.fit(X) # ajusta na variável de entrada
X_encoder = enc.transform(X) # aplica a transformação na variável de entrada
print(X_encoder)
# print(enc.inverse_transform(X_encoder))

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


9. Divida as variáveis X e y em dados de treino e de teste utilizando o método "train_test_split", gerando as variáveis X_train, X_test, y_train e y_test. Você define a proporção de dados de treino e de teste;

In [ ]:
# TESTE FEITO COM 3 QUARTIL DA AMOSTRA
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

print("Treino X = " + str(X_train.shape))
print("Teste  X = " + str(X_test.shape))
print("Treino y = " + str(y_train.shape))
print("Teste  y = " + str(y_test.shape))

Treino X = (7489, 1)
Teste  X = (2497, 1)
Treino y = (7489,)
Teste  y = (2497,)


10. Faça a padronização (escalonamento) dos dados das variáveis X_train e X_test utilizando a classe StandardScaler do scikit-learn;

In [ ]:
sc = StandardScaler()
sc.fit(X_train)
X_train_scaled = sc.transform(X_train)
X_train_scaled

array([[ 0.30954694],
       [-0.90036801],
       [ 1.51946189],
       ...,
       [-0.90036801],
       [-0.90036801],
       [-0.90036801]])

In [ ]:
sc = StandardScaler()
sc.fit(X_test)
X_test_scaled = sc.transform(X_test)
X_test_scaled

array([[-0.90596571],
       [ 0.29733024],
       [ 0.29733024],
       ...,
       [-0.90596571],
       [-0.90596571],
       [ 0.29733024]])